version: '3.8' # Specifies the Docker Compose version

services:
  opencart:  # Defines the Opencart service
    build:  # Specifies how to build the service
      context: .  # Specifies the context for the build, which is the current directory
      dockerfile: Dockerfile  # Specifies the Dockerfile to use for building the service
    ports:  # Exposes ports from the container to the host
      - 8566:80  # Maps port 80 in the container to port 8566 on the host
    depends_on:  # Specifies dependencies for the service
      - mysql  # Specifies that this service depends on the MySQL service
    environment:  # Sets environment variables for the service
      - MYSQL_HOST=mysql  # Specifies the hostname of the MySQL service
    volumes:  # Mounts volumes to the container
      - opencart_data:/var/www/html  # Mounts the opencart_data volume to /var/www/html in the container

  mysql:  # Defines the MySQL service
    image: mysql:5.7  # Specifies the Docker image to use for the service
    hostname: mysql  # Sets the hostname of the container
    environment:  # Sets environment variables for the service
      MYSQL_ROOT_PASSWORD: VerySecurePass  # Sets the root password for MySQL
      MYSQL_DATABASE: opencart  # Creates a database named "opencart"
      MYSQL_USER: example_opencart_user  # Creates a MySQL user named "example_opencart_user"
      MYSQL_PASSWORD: example_opencart_password  # Sets the password for the MySQL user
    volumes:  # Mounts volumes to the container
      - mysql_data:/var/lib/mysql  # Mounts the mysql_data volume to /var/lib/mysql in the container

  phpmyadmin:  # Defines the PhpMyAdmin service
    image: phpmyadmin/phpmyadmin  # Specifies the Docker image to use for the service
    ports:  # Exposes ports from the container to the host
      - 8080:80  # Maps port 80 in the container to port 8080 on the host
    environment:  # Sets environment variables for the service
      PMA_HOST: mysql  # Specifies the hostname of the MySQL service for PhpMyAdmin
      PMA_USER: root  # Specifies the MySQL root user for PhpMyAdmin
      PMA_PASSWORD: VerySecurePass  # Specifies the password for the MySQL root user
                  
  ftpserver:  # Defines the FTP server service
    image: fauria/vsftpd  # Specifies the Docker image to use for the service
    ports:  # Exposes ports from the container to the host
      - "21:21"  # Maps port 21 in the container to port 21 on the host
    environment:  # Sets environment variables for the service
      FTP_USER: "ftpuser"  # Specifies the FTP username
      FTP_PASS: "ftppassword"  # Specifies the FTP password
      PASV_ADDRESS: "your_vm_ip"  # Specifies the IP address of the FTP server
    volumes:  # Mounts volumes to the container
      - opencart_data:/home/ftpuser/opencart  # Mounts the opencart_data volume to /home/ftpuser/opencart in the container

volumes:  # Defines named volumes for data persistence
  mysql_data:  # Defines a named volume for MySQL data
  opencart_data:  # Defines a named volume for Opencart data
